// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("MachineFactoryTutorial")]
[assembly: AssemblyDescriptionAttribute("Windows Machine Factory Tutorial")]
[assembly: GuidAttribute("1acd961c-b169-44ce-84f9-ed8e3f95aeb1")]
[assembly: AssemblyProductAttribute("MachineFactoryTutorial")]
[assembly: AssemblyVersionAttribute("0.0")]
[assembly: AssemblyFileVersionAttribute("0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0";
    }
}
